all: clean build run

clean: 
	@rm -f data/hasilJson.json

build: # compile to binary (if you use interpreter, then do not implement it)

run: 
	@cd data && python ../src/src.py < ../src/inputIndonesia.txt